mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^quiz/', include('quiz.urls')),
	url(r'^polls/', include('polls.urls')),
    url(r'^broadcast/', include('broadcast.urls')),
    url(r'^admin/', admin.site.urls),
]

quiz/urls.py
from django.conf.urls import url

from . import views

app_name = 'quiz'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.TakeView.as_view(), name='take'),
    url(r'^edit/$', views.EditView.as_view(), name='edit'),
    url(r'^(?P<problem_id>[0-9]+)/choose/$', views.choose, name='choose'),
    url(r'^(?P<pk>[0-9]+)/results/', views.ResultsView.as_view(), name='results'),
    url(r'^edit/add_problem/$', views.AddProblemView.as_view(), name='add_problem'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.EditProblemView.as_view(), name='edit_problem'),
    url(r'^(?P<problem_id>[0-9]+)/delete_problem/$', views.deleteProblem, name='delete_problem'),
    url(r'^edit/add_problem/add_logic$', views.addLogic, name='add_logic')
]

quiz/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import datetime

class Problem(models.Model):
    problem_text = models.CharField(max_length=200)
    cur_score = models.IntegerField(default=0)
    num_problems = models.IntegerField(default=1)
    def __str__(self):
    	return self.problem_text

class Answer(models.Model):
	problem = models.ForeignKey(Problem, on_delete=models.CASCADE, null=True)
	is_correct = models.BooleanField(default=False)
	answer_text = models.CharField(max_length=200)
	def __str__(self):
		return self.answer_text

quiz/forms.py
from django import forms
from .models import Problem, Answer

class ProblemForm(forms.Form):
	text = forms.CharField(max_length=200)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import loader
from .models import Question, Choice
from django.views import generic
from django.utils import timezone

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		#Return the last five published questions.
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('pub_date')[:5]


class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
        #Excludes any questions that aren't published yet.
		return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form.
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

#Everything after line 1 was added by me

quiz/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import loader
from .models import Problem, Answer
from django.views import generic
from django.utils import timezone
from .forms import ProblemForm

#VIEW STUFF
class IndexView(generic.ListView):
	template_name = 'quiz/index.html'
	context_object_name = 'problem_list'
	def get_queryset(self):
		return Problem.objects.all()

class TakeView(generic.DetailView):
	model = Problem
	template_name = 'quiz/take.html'
	def get_queryset(self):
		return Problem.objects.all()

class EditView(generic.ListView):
	template_name = 'quiz/edit.html'
	context_object_name = 'problem_list'
	def get_queryset(self):
		return Problem.objects.all()

class ResultsView(generic.DetailView):
	model = Problem
	template_name = 'quiz/results.html'

class AddProblemView(generic.ListView):
	template_name = 'quiz/add_problem.html'
	context_object_name = 'problem_list'
	def get_queryset(self):
		return Problem.objects.all()

class EditProblemView(generic.DetailView):
	model = Problem
	template_name = 'quiz/edit_problem.html'


#Delete function. Since the Answer objects are related to Problem, they get deleted too.
def deleteProblem(request, problem_id):
	problem = get_object_or_404(Problem, pk=problem_id)
	problem.delete()
	return HttpResponseRedirect(reverse('quiz:edit'))

#This function is called when the user selects the 'Add Question' button on add_question.html
#Checks to make sure the information was filled in correctly and gives an error message if otherwise
def addLogic(request):
	problem = None
	problemCanBeMade = False
	if len(request.POST['problem_value']) < 1:
		return render(request, 'quiz/add_problem.html', {
			'error_message': "You didn't provide a question.",
		})
	for i in range(1,5):
		if len(request.POST['answer_value'+str(i)]) > 0:
			print request.POST.get('is_correct', 0)
			if request.POST.get('is_correct', 0) > 0:
				problemCanBeMade = True
				break
	if problemCanBeMade:
		problem = Problem(problem_text=request.POST['problem_value'])
		problem.save()
		for i in range(1,5):
			if len(request.POST['answer_value'+str(i)]) > 0:
				answer = Answer(answer_text=request.POST['answer_value'+str(i)])
				if int(request.POST.get('is_correct', 0)) == i:
					answer.is_correct = True
				answer.save()
				problem.answer_set.add(answer)
				problem.save()
			elif int(request.POST.get('is_correct', 0)) == i:
				problem.delete()
				return render(request, 'quiz/add_problem.html', {
					'error_message': "The correct answer did not have a value.",
				})
		return HttpResponseRedirect(reverse('quiz:edit'))
	else:
		return render(request, 'quiz/add_problem.html', {
			'error_message': "You didn't provide a correct answer.",
		})


#This function is called when the user selects the 'Next Question' button on take.html
#It adds up the score and number of problems as it goes
def choose(request, problem_id):
	problem = get_object_or_404(Problem, pk=problem_id)
	min_id = problem.id

	for p in Problem.objects.all():
		if p.id < min_id:
			min_id = p.id
	if problem.id == min_id:
		problem.cur_score = 0
		problem.num_problems = 1
	try:
		selected_answer = problem.answer_set.get(pk=request.POST['answer'])
	except (KeyError, Answer.DoesNotExist):
		return render(request, 'quiz/take.html', {
			'problem': problem,
			'error_message': "You didn't select an answer.",
		})
	else:
		if selected_answer.is_correct:
			if problem.id > min_id:
				last_problem = Problem.objects.filter(id__lt=problem.id).order_by("-id")[0:1].get()
				problem.cur_score = last_problem.cur_score + 1
				#problem.cur_score = Problem.objects.get(id=(problem.id - 1)).cur_score + 1
			else:
				problem.cur_score = 1
		else:
			if problem.id > min_id:
				last_problem = Problem.objects.filter(id__lt=problem.id).order_by("-id")[0:1].get()
				problem.cur_score = last_problem.cur_score
				#problem.cur_score = Problem.objects.get(id=(problem.id - 1)).cur_score
		if problem.id > min_id:
			last_problem = Problem.objects.filter(id__lt=problem.id).order_by("-id")[0:1].get()
			problem.num_problems = last_problem.num_problems + 1
		try:
			next_problem = Problem.objects.filter(id__gt=problem.id).order_by("id")[0:1].get()
			return HttpResponseRedirect(reverse('quiz:take', args=(next_problem.id,)))
		except Problem.DoesNotExist:
			next_problem = problem
			return HttpResponseRedirect(reverse('quiz:results', args=(next_problem.id,)))

quiz/templates/quiz/add_problem.html
<h2>Add a Problem:</h2>

{% if error_message %}<p style="color:red">{{ error_message }}</p>{% endif %}

<form action="{% url 'quiz:add_logic' %}" method="post">
{% csrf_token %}
	<label for="problem_value">Problem: </label>
	<input type="text" name="problem_value" id="problem_value"/>
	<br>
	<br>

	<p>Choices: (mark one correct)</p>
	<input type="radio" name="is_correct" id="is_correct1" value="1" />
	<input type="text" name="answer_value1" id="answer_value1"/><br />
	<input type="radio" name="is_correct" id="is_correct2" value="2" />
	<input type="text" name="answer_value2" id="answer_value2"/><br />
	<input type="radio" name="is_correct" id="is_correct3" value="3" />
	<input type="text" name="answer_value3" id="answer_value3"/><br />
	<input type="radio" name="is_correct" id="is_correct4" value="4" />
	<input type="text" name="answer_value4" id="answer_value4"/><br />

	<br>
<input type="submit" value="Add Question" />
</form>
<br>
<a style="color:blue" href="{% url 'quiz:edit' %}">Back to Edit Page</a>

quiz/templates/quiz/edit.html
<h2>Problems:</h2>

{% if problem_list %}
	<ol>
		{% for problem in problem_list %}
		<li><a style="color:blue" href="{% url 'quiz:edit_problem' problem.pk %}">{{ problem.problem_text }}</a></li>
		{% endfor %}
	</ol>
{% else %}
	<p>There are currently no problems in the test.</p>
{% endif %}
<ul>
	<li><a style="color:blue" href="{% url 'quiz:add_problem' %}">Add a Problem</a></li>
	<li><a style="color:blue" href="{% url 'quiz:index' %}">Back to Homepage</a></li>
</ul>

quiz/templates/quiz/edit_problem.html
<h2>{{ problem.problem_text }}</h2>

<form action="{% url 'quiz:delete_problem' problem.id %}" method="post">
{% csrf_token %}
<input type="submit" value="Delete This Question" />
</form>
<br>
<a style="color:blue" href="{% url 'quiz:edit' %}">Back to Edit Page</a>

quiz/templates/quiz/index.html
<h1>Simple Test App</h1>
<ul>
	{% if problem_list.first.id %}
	<li><a style="color:blue" href="{% url 'quiz:take' problem_list.first.id %}">Take the Test</a></li>
	{% else %}
	<li>Test is currently empty. Add questions in the 'Edit the Test' page.</li>
	{% endif %}
	<li><a style="color:blue" href="{% url 'quiz:edit' %}">Edit the Test</a></li>
</ul>

quiz/templates/quiz/results.html
<h2>Results:</h2>

<p>Final score is {{ problem.cur_score }} out of {{ problem.num_problems }} possible points.</p>

<a style="color:blue" href="{% url 'quiz:index' %}">Back home</a>

quiz/templates/quiz/take.html
{% if problem %}
<h4>{{ problem.problem_text }}</h4>

{% if error_message %}<p style="color:red">{{ error_message }}</p>{% endif %}

<form action="{% url 'quiz:choose' problem.id %}" method="post">
{% csrf_token %}
{% for answer in problem.answer_set.all %}
    <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
    <label for="answer{{ forloop.counter }}">{{ answer.answer_text }}</label><br />
{% endfor %}
<br>
<input type="submit" value="Next Question" />
</form>
<!--<br>
<p>Current score: {{ problem.cur_score }}/{{ problem.id|add:"-1" }}</p> -->
{% else %}
<p>Nothing here</p>
{% endif %}