broadcast/urls.py
from django.conf.urls import url

from . import views

app_name = 'broadcast'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^groupme_home/$', views.GroupMeHomeView.as_view(),name='groupme_home'),
    url(r'^groupme_home/save_group/$', views.saveGroups, name='save_groups'),
    url(r'^groupme_home/add_groupme_api/$', views.addGroupMeApi, name='add_groupme_api'),
    url(r'^groupme_home/wipe_groups/$', views.wipeGroups, name='wipe_groups'),
    url(r'^twitter_home/$', views.TwitterHomeView.as_view(),name='twitter_home'),
    url(r'^twitter_home/add_twitter/$', views.addTwitter, name='add_twitter'),
    url(r'^twitter_home/save_twitter/$', views.saveTwitter, name='save_twitter'),
    url(r'^twitter_home/remove_twitter/$', views.removeTwitter, name='remove_twitter'),
    url(r'^send_message/$', views.sendMessage, name='send_message'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^quiz/', include('quiz.urls')),
	url(r'^polls/', include('polls.urls')),
    url(r'^broadcast/', include('broadcast.urls')),
    url(r'^admin/', admin.site.urls),
]

quiz/urls.py
from django.conf.urls import url

from . import views

app_name = 'quiz'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.TakeView.as_view(), name='take'),
    url(r'^edit/$', views.EditView.as_view(), name='edit'),
    url(r'^(?P<problem_id>[0-9]+)/choose/$', views.choose, name='choose'),
    url(r'^(?P<pk>[0-9]+)/results/', views.ResultsView.as_view(), name='results'),
    url(r'^edit/add_problem/$', views.AddProblemView.as_view(), name='add_problem'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.EditProblemView.as_view(), name='edit_problem'),
    url(r'^(?P<problem_id>[0-9]+)/delete_problem/$', views.deleteProblem, name='delete_problem'),
    url(r'^edit/add_problem/add_logic$', views.addLogic, name='add_logic')
]

broadcast/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import datetime

"""class GroupMeAPI(models.Model):
	token_text = models.CharField(max_length=200)
	def __str__(self):
		return self.token_text"""

class Token(models.Model):
	token_text = models.CharField(max_length=200)
	def __str__(self):
		return token_text

class Group(models.Model):
	#groupmeapi = models.ForeignKey(GroupMeAPI, on_delete=models.CASCADE, null=True)
	group_name = models.CharField(max_length=200)
	group_id = models.CharField(max_length=200, null=True)
	active = models.BooleanField(default=False)
	def __str__(self):
		return self.group_name

class TwitterKeys(models.Model):
	consumer_key = models.CharField(max_length=200)
	consumer_secret = models.CharField(max_length=200)
	access_token_key = models.CharField(max_length=200)
	access_token_secret = models.CharField(max_length=200)
	active = models.BooleanField(default=True)
	screen_name = models.CharField(max_length=200, null=True)

broadcast/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import loader
from django.views import generic
from django.utils import timezone
from .models import Group, TwitterKeys
from .models import Token
from random import randint
import json
import twitter
from twitter import TwitterError
import requests
import argparse
import os
import sys


#REQUEST STUFF
URL = 'https://api.groupme.com/v3'

#HELPER FUNCTIONS
def get(response):
	return response.json()['response']

#VIEW CLASSES
class IndexView(generic.ListView):
	template_name = 'broadcast/index.html'
	context_object_name = 'groups'
	def get_queryset(self):
		return Group.objects.all()

class GroupMeHomeView(generic.ListView):
	context_object_name = 'groups'
	template_name = 'broadcast/groupme_home.html'
	def get_queryset(self):
		return Group.objects.all()

class TwitterHomeView(generic.ListView):
	context_object_name = 'twitter'
	template_name = 'broadcast/twitter_home.html'
	def get_queryset(self):
		return TwitterKeys.objects.first()

#VIEW FUNCTIONS
def addTwitter(request):
	#Get a TwitterKeys object with posted information, change its username, and save it to database
	key = TwitterKeys(consumer_key=request.POST['consumer_key'], consumer_secret=request.POST['consumer_secret'], access_token_key=request.POST['access_token_key'], access_token_secret=request.POST['access_token_secret'])
	api = twitter.Api(consumer_key=key.consumer_key,
	                      consumer_secret=key.consumer_secret,
	                      access_token_key=key.access_token_key,
	                      access_token_secret=key.access_token_secret)
	try:
		api.VerifyCredentials()
	except TwitterError as e:
		return HttpResponseRedirect(reverse('broadcast:twitter_home'))
	key.screen_name = json.loads(str(api.VerifyCredentials()))['screen_name']
	key.save()
	return HttpResponseRedirect(reverse('broadcast:twitter_home'))

def saveTwitter(request):
	#save the active state of the TwitterKeys objects
	key = TwitterKeys.objects.first()
	key.active = request.POST.get('active', False)
	key.save()
	return HttpResponseRedirect(reverse('broadcast:twitter_home'))

def removeTwitter(request):
	#remove the TwitterKeys object
	keys = TwitterKeys.objects.all()
	for key in keys:
		key.delete()
	return HttpResponseRedirect(reverse('broadcast:twitter_home'))

def sendMessage(request):
	#groupme side
	msgText = request.POST['message']
	#make random string for guid
	token = Token.objects.first()
	print "Sending message " + msgText
	for g in Group.objects.all():
		if g.active:
			print token.token_text
			guid = str(randint(-32000,32000))
			msgData = json.dumps({"message":{"source_guid":guid, "text": msgText}})
			print requests.post("https://api.groupme.com/v3/groups/" + g.group_id + "/messages?token=" + token.token_text, data=msgData, headers={'Content-Type': 'application/json'})
	#twitter side
	keys = TwitterKeys.objects.all()
	for key in keys:
		if key.active:
			api = twitter.Api(consumer_key=key.consumer_key,
		                      consumer_secret=key.consumer_secret,
		                      access_token_key=key.access_token_key,
		                      access_token_secret=key.access_token_secret)
			api.PostUpdate(msgText)
	return HttpResponseRedirect(reverse('broadcast:index'))

def wipeGroups(request):
	#remove API token from database
	tokens = Token.objects.all()
	for t in tokens:
		t.delete()
	#remove groups associated with API token from database
	for g in Group.objects.all():
		g.delete()
	return HttpResponseRedirect(reverse('broadcast:groupme_home'))

def saveGroups(request):
	#save active state for all groups
	checklist = request.POST.getlist('active')
	for g in Group.objects.all():
		g.active = (g.group_id in checklist)
		g.save()
	return HttpResponseRedirect(reverse('broadcast:groupme_home'))

def addGroupMeApi(request):
	#change the API token for the new groups to be used for messaging service
	token = request.POST['groupmeApiToken']
	tokenToAdd = Token(token_text=token)
	tokenToAdd.save()
	groups = get(requests.get(URL + '/groups' + '?token=' + token, params={'per_page' : 100}))
	if not groups:
		return HttpResponseRedirect(reverse('broadcast:groupme_home'))
	for g in groups:
		groupToAdd = Group(group_name=g['name'], group_id=g['group_id'])
		groupToAdd.save()
	return HttpResponseRedirect(reverse('broadcast:groupme_home'))

broadcast/templates/broadcast/groupme_home.html
<h1>GroupMe Groups</h1>

{% if groups %}
<p>Select groups you would like to send messages to.</p>
	<form action="{% url 'broadcast:save_groups' %}" method="post">
		{% csrf_token %}
		{% for group in groups.all %}
			<input type="checkbox" name="active" value="{{ group.group_id }}" {% if group.active %}checked{% endif %}>{{ group.group_name }}<br />
		{% endfor %}
		<br>
		<input type="submit" value="Save Settings" />
	</form>
	<form action="{% url 'broadcast:wipe_groups' %}" method="post">
		{% csrf_token %}
		<input type="submit" value="Delete Groups">
	</form>
{% else %}
<p style="color: red">Not currently logged in or no valid API token given. Or maybe you don't have any groups :(</p>
<form action="{% url 'broadcast:add_groupme_api' %}" method="post">
	{% csrf_token %}
	GroupMe API Token: <input type="text" name="groupmeApiToken" id="groupmeApiToken" />
	<input type="submit" value="Add GroupMe API Token" />
</form>
{% endif %}
<br>
<br>
<a style="color: blue" href="{% url 'broadcast:index' %}">Back to home</a>

broadcast/templates/broadcast/index.html
<h1>Broadcast</h1>
<ul>
	<li><a style="color:blue" href="{% url 'broadcast:groupme_home'%}">GroupMe Settings</a></li>
	<li><a style="color:blue" href="{% url 'broadcast:twitter_home' %}">Twitter Settings</a></li>
</ul>
<br>
<form action="{% url 'broadcast:send_message' %}" method="post">
	{% csrf_token %}
	Broadcast this message to GroupMe and Twitter: <input type="text" name="message" id="message" />
	<input type="submit" value="Send Message" />
</form>

broadcast/templates/broadcast/twitter_home.html
<h1>Twitter Settings</h1>

{% if twitter %}
<p>Currently signed in as {{ twitter.screen_name }}.</p>
<form action="{% url 'broadcast:remove_twitter' %}" method="post">
	{% csrf_token %}
	<input type="submit" value="Remove Credentials">
</form>
<br>
<form action="{% url 'broadcast:save_twitter' %}" method="post">
	{% csrf_token %}
	<input type="checkbox" name="active" {% if twitter.active %}checked{% endif %}>Send to {{ twitter.screen_name }}'s Twitter<br />
	<br>
	<input type="submit" value="Save Settings">
</form>
{% else %}
<p>Input Twitter API Information</p>
<form action="{% url 'broadcast:add_twitter' %}" method="post">
	{% csrf_token %}
	Consumer key: <input type="text" name="consumer_key" id="consumer_key" /><br>
	Consumer secret: <input type="text" name="consumer_secret" id="consumer_secret" /><br>
	Access token key: <input type="text" name="access_token_key" id="access_token_key" /><br>
	Access token secret: <input type="text" name="access_token_secret" id="access_token_secret" /><br>
	<br>
	<input type="submit" value="Verify Credentials" />
</form>
{% endif %}
<br>
<br>
<a style="color: blue" href="{% url 'broadcast:index' %}">Back to home</a>